clear
raw=imread('picture.jpg');%读取当前目录下名为picture.jpg的图片
raw_r=raw(:,:,1);
raw_g=raw(:,:,2);
raw_b=raw(:,:,3);
%保存纯数据矩阵
save('data(raw).mat','raw_r','raw_g','raw_b');
[U_r1,S_r1,V_r1]=svd(double(raw_r));
[U_g1,S_g1,V_g1]=svd(double(raw_g));
[U_b1,S_b1,V_b1]=svd(double(raw_b));
[r,c]=size(S_r1);
S=zeros(r,c);
S=(S_r1+S_g1+S_b1)/3;
length=min(r,c);
s=zeros(length,1);
for i = 1:length
    s(i,1)=S(i,i);
end
plot(1:1:length,s);
a=input('你要保留svd分解的前几项:');%结果保留svd分解的前a项
n=input('储存的数据中，小数的位数：');
U_r=round(single(U_r1(:,1:a)),n);
S_r=round(single(S_r1(1:a,1:a)),n);
V_r=round(single(V_r1(:,1:a)),n);
U_g=round(single(U_g1(:,1:a)),n);
S_g=round(single(S_g1(1:a,1:a)),n);
V_g=round(single(V_g1(:,1:a)),n);
U_b=round(single(U_b1(:,1:a)),n);
S_b=round(single(S_b1(1:a,1:a)),n);
V_b=round(single(V_b1(:,1:a)),n);
%将压缩的数据矩阵保存下来
save('data(condensed).mat','U_r','S_r','V_r','U_g','S_g','V_g','U_b','S_b','V_b');
U_r=double(U_r);
S_r=double(S_r);
V_r=double(V_r);
U_g=double(U_g);
S_g=double(S_g);
V_g=double(V_g);
U_b=double(U_b);
S_b=double(S_b);
V_b=double(V_b);
small_r=(U_r)*(S_r)*(V_r)';
small_g=(U_g)*(S_g)*(V_g)';
small_b=(U_b)*(S_b)*(V_b)';
small(:,:,1)=small_r(:,:,1);
small(:,:,2)=small_g(:,:,1);
small(:,:,3)=small_b(:,:,1);
small_8=uint8(small);
%作图
subplot(1,2,2)
imshow(small_8);
subplot(1,2,1)
imshow(raw);
box off